package presentacion;
/**
 *
 * @author Bolil
 */
public class PanelBotones extends javax.swing.JPanel {

    /**
     * Creates new form NewJPanel
     */
    public PanelBotones() {
        initComponents();
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonCrear1 = new javax.swing.JButton();
        jButtonCrear2 = new javax.swing.JButton();
        jButtonCrear = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setLayout(null);

        jButtonCrear1.setFont(new java.awt.Font("OCR A Extended", 1, 24)); // NOI18N
        jButtonCrear1.setForeground(new java.awt.Color(255, 255, 255));
        jButtonCrear1.setText("Salir");
        jButtonCrear1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        jButtonCrear1.setContentAreaFilled(false);
        jButtonCrear1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCrear1ActionPerformed(evt);
            }
        });
        add(jButtonCrear1);
        jButtonCrear1.setBounds(780, 30, 220, 31);

        jButtonCrear2.setFont(new java.awt.Font("OCR A Extended", 1, 24)); // NOI18N
        jButtonCrear2.setForeground(new java.awt.Color(255, 255, 255));
        jButtonCrear2.setText("Cambiar Tamaño");
        jButtonCrear2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        jButtonCrear2.setContentAreaFilled(false);
        jButtonCrear2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCrear2ActionPerformed(evt);
            }
        });
        add(jButtonCrear2);
        jButtonCrear2.setBounds(450, 30, 270, 31);

        jButtonCrear.setFont(new java.awt.Font("OCR A Extended", 1, 24)); // NOI18N
        jButtonCrear.setForeground(new java.awt.Color(255, 255, 255));
        jButtonCrear.setText("Calcular Camino");
        jButtonCrear.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        jButtonCrear.setContentAreaFilled(false);
        jButtonCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCrearActionPerformed(evt);
            }
        });
        add(jButtonCrear);
        jButtonCrear.setBounds(30, 30, 350, 31);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondoJPanel.jpg"))); // NOI18N
        add(jLabel1);
        jLabel1.setBounds(0, 0, 1022, 99);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCrearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonCrearActionPerformed

    private void jButtonCrear1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCrear1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonCrear1ActionPerformed

    private void jButtonCrear2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCrear2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonCrear2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCrear;
    private javax.swing.JButton jButtonCrear1;
    private javax.swing.JButton jButtonCrear2;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
